// One short English explanation for each grammar structure of the catalog, shown next to its English name
// (see build-grammar-catalog.mjs). Keyed by point id, which is stable across rebuilds. Clause types share
// one explanation per type. Fixed patterns (又……又……) have none: the pattern says it itself.

export const NOTES = {
  g29: "The predicate is a verb: 我学习汉语。",
  g30: "The predicate is an adjective, usually with 很: 她很高。",
  g31: "A sentence without the usual subject and predicate: 下雨了。",
  g32: "A statement that tells something.",
  g33: "Questions: yes/no (吗), question word, either-or (还是), verb-not-verb.",
  g34: "A request or command: 请坐。别走！",
  g35: "An exclamation: 太好了！多漂亮啊！",
  g36: "A 是 B says what something is (他是老师), describes it, or says it exists.",
  g37: "有 for owning (我有一本书) or existing (桌子上有一本书).",
  g38: "A comparison: A比B + adjective (他比我高); A没有B + adjective for 'not as … as'.",
  g40: "Final 了 marks a new situation or a change: 下雨了。",
  g41: "了 right after a verb marks a completed action: 我吃了饭。",
  g42: "在/正在 + verb, or final 呢, for an action in progress: 他在看书。",
  g43: "How to say prices: 三块五, 一百二十块。",
  g44: "How to say dates, weekdays and clock time: 三月五号, 星期二, 三点一刻。",
  g45: "Add 吗 to a statement to ask a yes/no question: 你累吗？",
  g46: "Question words (什么, 谁, 哪儿, 几, 怎么) stand where the answer goes: 你去哪儿？",
  g47: "A还是B? asks which of two options: 你喝茶还是咖啡？",
  g48: "Verb + 不 + the same verb asks yes or no: 你去不去？",
  g97: "A verb followed by a word that gives the result: 听懂, 看错, 做完。",
  g98: "A verb followed by 来/去/上/下/进/出… shows which way it moves: 走进, 拿来。",
  g99: "Verb + 得 + adjective says how an action goes: 他跑得很快。",
  g100: "A verb followed by how many times: 我去过三次。",
  g101: "An adjective followed by an amount, for 'by how much': 他大三岁。",
  g102: "A noun as the predicate, for dates, age and price: 今天星期三。",
  g103: "有 for reaching a measure: 他有一米八高。",
  g104: "Place + 有 or verb + 着 + thing says what is where: 桌子上放着一本书。",
  g105: "Several verbs in a row with one subject, done in order: 我下班回家吃饭。",
  g106: "More comparisons: A比B + adjective + amount, A比B更/还 + adjective, A不如B, A有B那么 + adjective.",
  g107: "Sameness: A跟B一样 (+ adjective).",
  g108: "是……的 stresses when, where, how or by whom it happened: 我是昨天来的。",
  g109: "A verb with two objects, who gets what: 他给我一本书。",
  g118: "Verb + 着 for a lasting state or action: 门开着。",
  g119: "Verb + 过 says you have done it before: 我去过中国。",
  g120: "Ordinal numbers with 第: 第一, 第二。",
  g121: "A rough number with 多: 十多个, 三个多月。",
  g122: "就 stresses 'just, exactly': 我就要这个。",
  g124: "A tag asks for agreement: 我们走，好吗？",
  g125: "Questions about time, kind and reason: 你什么时候来？为什么？",
  g126: "Noun or pronoun + 呢 asks 'and what about …?': 我很好，你呢？",
  g127: "是不是 asks for confirmation: 你是不是累了？",
  g128: "A statement + 吧 asks to confirm a guess: 你是学生吧？",
  g176: "A verb followed by 到/住/走 as the result: 找到, 记住, 拿走。",
  g177: "A verb followed by a two-part direction (进来, 回去, 起来): 他跑进来了。",
  g178: "Verb + 得/不 + result says can or cannot: 听得懂, 看不见。",
  g179: "Adjective + 得很/极了/死了 for 'very': 好得很, 累死了。",
  g180: "With an object and a count of times: 我去过北京三次。",
  g181: "Verb + how long it lasted: 我学了三年汉语。",
  g182: "How long since something ended or happened: 他毕业三年了。",
  g183: "The predicate is itself a subject and predicate: 我头疼。",
  g184: "把 puts the object first and says what is done to it: 我把书放在桌子上。",
  g185: "A passive with 被/叫/让: 书被借走了。",
  g186: "Two verbs where the first is the way or the second the purpose: 坐飞机去, 去买东西。",
  g187: "A causative: 请/叫/让/派 + person + verb: 老师叫我回答。",
  g188: "Comparison with verb + 得, with 不比, or with an amount: 他跑得比我快。",
  g189: "Repeat the verb when it has an object and a complement: 他说汉语说得很好。",
  g204: "Rough numbers: 大概/大约, neighbouring numbers (五六个), 左右。",
  g206: "A rhetorical question for emphasis: 这不是你的书吗？",
  g207: "是 stresses the word after it: 我是真的不知道。",
  g208: "A statement said with a rising tone becomes a question: 你去？",
  g248: "A direction word with a figurative result: 想起, 看上, 说出。",
  g249: "把 with a doubled verb or 了/着: 你把房间收拾收拾。",
  g250: "A passive with 被 + verb + more: 钱包被偷了。",
  g251: "Place + verb + thing says something appears or disappears: 前面来了一辆车。",
  g252: "Verb + person + verb: praise or blame, or naming someone: 叫他小王。",
  g253: "是……的 gives the speaker's view or attitude: 这样做是不对的。",
  g272: "Number + 来 + measure word for 'about': 十来个人。",
  g273: "Decimals, fractions, percentages and multiples: 零点五, 三分之一, 百分之十, 两倍。",
  g274: "A rhetorical question with a question word: 谁不知道？",
  g275: "Two negatives make a strong yes: 不能不去。",
  g321: "A direction word for time: starting (唱起歌来) or continuing (说下去)。",
  g322: "Verb + 得/不得 for 'may' or 'may not': 这里去不得。",
  g323: "Degree after 得 or a verb: 好得不得了, 累坏了。",
  g324: "A longer description after 得: 他气得说不出话来。",
  g325: "有 with 着, in written style: 他有着丰富的经验。",
  g326: "把 with an adverb in front of the verb, or 一 + verb: 把门一关。",
  g327: "A passive meaning without 被: 衣服洗好了。",
  g328: "Two verb phrases linked by cause, contrast or condition.",
  g329: "A causative with 使/令/让: 这件事让我很高兴。",
  g330: "跟……相比, or A + adjective + B + amount.",
  g344: "再也不/没 means 'never again': 我再也不去了。",
  g345: "可 stresses the statement: 你可来了！",
  g346: "怎么都/也 + negative means 'no matter how, still not': 怎么都睡不着。",
  g397: "A direction word that shows a state: 天暗下来了, 好起来。",
  g398: "把 for causing something, often with a non-living subject: 这件事把他气坏了。",
  g399: "被/叫/让 + doer + 给 + verb: 杯子让他给摔了。",
  g458: "得不行 / 得要命 for 'extremely': 累得不行。",
  g459: "个 introduces the complement: 玩个痛快, 睡个够。",
  g460: "A causative 把 sentence whose object is the doer, ending in verb + 了.",
  g461: "A written passive: 被……所……, 为……所……: 为人所知。",
  g462: "More comparisons: 比起……(来), A + adjective + 于 + B, A比 + noun + 还 + noun.",
  g499: "A rhetorical 'why bother?': 何必/何苦……呢？",
};

export const CLAUSE_NOTES = {
  并列复句: "Two clauses side by side: 一边……一边……",
  承接复句: "Actions one after another: 先……再……",
  递进复句: "The second clause goes a step further: 不但……而且……",
  选择复句: "A choice between options: 或者……或者……",
  转折复句: "A contrast: 虽然……但是……",
  假设复句: "If … then …: 如果……就……",
  条件复句: "A condition and its result: 只要……就……",
  因果复句: "A cause and its result: 因为……所以……",
  紧缩复句: "Two clauses squeezed into one, with no pause: 越多越好。",
  目的复句: "The purpose of an action: 为了……",
  让步复句: "Even if … still …: 即使……也……",
  二重复句: "A complex sentence with two layers of clauses.",
  解说复句: "The second clause explains the first.",
  多重复句: "A complex sentence with three or more layers of clauses.",
};
